#!/bin/bash

app_dir="/usr/share/applications";
tmp_compare="/tmp/applications-modified-time";

function update-menu {
    for file in $(ls /usr/share/desktop-menu/templates)
        do
            desktop=$(echo $file|cut -d "." -f1)
            echo "Updating $desktop menu"
            desktop-menu --write-out-global --no-display --desktop-code $desktop;
        done
} 

case $1 in 
set)
    stat -c %Y $app_dir > $tmp_compare;
;;
check)
    current_date=$(stat -c %Y $app_dir)
    past_date=$(cat $tmp_compare)
    if [ "$current_date" != "$past_date" ]; then
        update-menu
    else 
        exit 0
    fi
;;
force)
    update-menu
;;
*)
    echo "Not an option";
    echo "set - sets the log for pre apt time stamp"
    echo "check - checks to see if the applications directory has changed in post apt"
    echo "force - forces an update"
;;
esac

