#!/bin/bash

app_dir="/usr/share/applications";
tmp_compare="/tmp/applications-modified-time";


freshendb () {
    # freshen the mlocate database
    if [ -f /var/lib/mlocate/mlocate.db ]; then
        updatedb;
    fi
}

case $1 in
set)
    stat -c %Y $app_dir > $tmp_compare;
;;
check)
    current_date=$(stat -c %Y $app_dir)
    past_date=$(cat $tmp_compare)
    if [ "$current_date" != "$past_date" ]; then
        /usr/local/bin/desktop-menu --write-out-global;
        freshendb;
    else
        exit 0
    fi
;;
force)
    /usr/local/bin/desktop-menu --write-out-global;
    freshendb;
;;
*)
    echo "Not an option";
    echo "set - sets the log for pre apt time stamp"
    echo "check - checks to see if the applications directory has changed in post apt"
    echo "force - forces an update"
;;
esac

