#!/bin/bash
cp /usr/share/applications/spacefm.desktop $XDG_DESKTOP_DIR;
cp /usr/share/applications/iceweasel.desktop $XDG_DESKTOP_DIR;
cp /usr/share/applications/antix/Install.desktop $XDG_DESKTOP_DIR;
cp /usr/share/applications/roxterm.desktop $XDG_DESKTOP_DIR;
cp /usr/share/applications/antix/xmms.desktop $XDG_DESKTOP_DIR;
